### ISSUE TITLE
Helm chart requires you to create a service account to use a service account

### ISSUE THREAD

**Issue by Setheck** [jmriebold/sqs-prometheus-exporter#11]
I manage an eks cluster using terraform. I use the module https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/irsa to create my service accounts. 
The current setup of the sqs-prometheus-exporter helm chart requires you set `serviceAccount.create` to true to set the service account, but in the same fashion it forces creation of a k8 Service Account object.
Making it impossible to create a service account by other means and bind it into the helm chart.

It would be ideal to decouple the name of the service account, similar to other helm charts, you could add a `name` sibling to `serviceAccount.create` default the value of the ServiceAccount object to it, and only create that service account object when create is true.

It's a pretty simple change, i'll submit a pr

**Comment by jmriebold** [comment]
I've just released v1.1.4 of the chart, including your changes.
